security:
    acl:
        connection: default
    encoders:
        Symfony\Component\Security\Core\User\User: md5
        FOS\UserBundle\Model\UserInterface: md5
        # Ztec\Security\ActiveDirectoryBundle\Security\User\adUser : md5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SONATA_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: [ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        #my_active_directory_provider :
        # ldap :
        #     id: ztec.security.active.directory.user.provider  
        fos_userbundle:
            id: fos_user.user_manager
        # in_memory:
        #     memory:
        #         users:
        #             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #             admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
       main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
    #     admin:
    #         pattern:            /admin(.*)
    #         context:            user
    #         form_login:
    #             provider:       fos_userbundle
    #             login_path:     /admin/login
    #             use_forward:    false
    #             check_path:     /admin/login_check
    #             failure_path:   null
    #         logout:
    #             path:           /admin/logout
    #         anonymous:          true
        # dev:
        #     pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

        # login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        # ldap:
        #     provider: ldap
        #     pattern: ^/
        #     anonymous: ~
        #     active_directory:
        #         login_path: login
        #         check_path: login_check
        #         default_target_path: homepage
        #         always_use_default_target_path: true
        #     logout:
        #         path: /logout
        #         target: login       
        #     remember_me:
        #         key: bibliotecaSOA
        #         lifetime: 3600
        # secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:

        #         check_path: _security_check
        #         login_path: _demo_login
        #     logout:
        #         path:   _demo_logout
        #         target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_A    NONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        # - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
